### PR TITLE
Fix WP CLI redirect

### LINKED ISSUE #40: WP-CLI plugin activation breaks due to redirect
When activating all plugins on a site using wp-cli, the process breaks after activating multicollab due to a redirect. The remainder of the plugins do not get activated due to this issue.

`Plugin 'xxx' activated.
Warning: Some code is trying to do a URL redirect. Backtrace:
#0  WP_CLI\Utils\wp_redirect_handler(http://[domain.com]/wp-admin/admin.php?activated=1&page=editorial-comments) called at [/path/to/core/wp-includes/class-wp-hook.php:305]`

### PR DESCRIPTION
**Pull request by macr1408**
Prevents WP CLI redirect. Fixes #40

### CODE REVIEW

**Comment by lkraav** [comment]
I don't know, needing such checks may be a sign that an immediate post-activation redirect is Bad Practice in the first place.

**Comment by macr1408** [comment]
I don't think redirecting post-activation is a bad practice, I mean, many big plugins use it and it's a common practice nowadays. 

Actually is pretty common to see the same conditional in those plugins. Anyways, yes, both solutions would work, I'd like to hear contributors' input on this issue

**Comment by lkraav** [comment]
> I don't think redirecting post-activation is a bad practice, I mean, many big plugins use it and it's a common practice nowadays.

OK, I just haven't had a reason yet to look at that part of codebases.

**Comment by poojabhimani12** [comment]
Fixed it in Version2.0.3.

**Pull request closed without merging**
